MODINVSTOR-1225 - Provide necessary permission to call endpoint bulk instances upsert
folio-org/mod-marc-migrations pull request #70
Opened 2024-08-19 13:41 UTC by RuslanLavrov

## Purpose
to provide permission that is required to call bulk instances upsert endpoint during migration flow initiated for instances to save results of instances remapping

## Learning
[MODINVSTOR-1225](https://issues.folio.org/browse/MODINVSTOR-1225)

Relates to: https://github.com/folio-org/mod-inventory-storage/pull/1062

2024-08-19 13:51 UTC, KaterynaSenchenko approved these changes

2024-08-20 08:10 UTC, psmagin approved these changes

2024-08-20 08:10 UTC, psmagin requested changes
Please create ticket in mod-marc-migration project

2024-08-21 07:33 UTC, Aliaksandr-Fedasiuk approved these changes

2024-08-21 14:09 UTC, dmytrokrutii approved these changes

2024-08-22 12:33 UTC, VRohach approved these changes

2024-08-30 11:20 UTC, psmagin approved these changes

2024-08-30 11:27 UTC, merged